name: Deploy to GitHub Pages
run-name: Deploy to GitHub Pages



on:
  push:
    branches: main

  workflow_dispatch:



permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  generate-repoData:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rpeository
        uses: actions/checkout@v4.1.1

      - name: Generate `repoData/output.json`
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const {default: main} = await import(
              `${{github.workspace}}/.github/workflows/generate-repoData.js`
            )

            await main({github, context})



  # astro-build:
  #   needs: generate-repoData
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Building website
  #       uses: withastro/action@v2.0.0

  astro-build:
    needs: generate-repoData
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@4.0.2
        with:
          node-version: lts
          cache: npm
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        shell: "bash"
        working-directory: .
        run: npm ci

      - name: Build Astro project
        shell: "bash"
        working-directory: .
        run: npm run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./dist/"



  deployToGitHubPages:
    needs: astro-build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
