name: Deploy to GitHub Pages
run-name: Deploy to GitHub Pages



on:
  push:
    branches: main

  workflow_dispatch:



permissions:
  contents: write
  pages: write
  id-token: write



jobs:
  pre-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rpeository
        uses: actions/checkout@v4.1.1

      - name: Generate `repoData/output.json`
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const {default: main} = await import(
              `${{github.workspace}}/.github/workflows/generate-repoData.js`
            )

            await main({github, context})

      - name: Build Astro project
        uses: withastro/action@v2.0.0



  deploy:
    needs: pre-deploy
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
